spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/fundo_user_db?createDatabaseIfNotExist=true
    username: root
    password: Rudresh@2005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/