package com.springmvc.model;

/**
 * User — the domain model representing a registered user.
 *
 * =====================================================================
 * WHY THIS CLASS EXISTS
 * =====================================================================
 * The User model is a plain Java object (POJO) that mirrors the
 * "users" table in the database.  It is used to:
 *
 *  1. Transfer data between the DAO layer and the Service layer.
 *  2. Store the logged-in user in HttpSession.
 *  3. Bind HTML form data in Spring MVC (via @ModelAttribute).
 *
 * =====================================================================
 * NO JPA / HIBERNATE
 * =====================================================================
 * This class deliberately has NO @Entity, @Table, or @Column
 * annotations.  We use plain JDBC, so the mapping between this
 * class and the database table is done manually in the DAO layer
 * using ResultSet.
 *
 * =====================================================================
 * WHY GETTERS / SETTERS?
 * =====================================================================
 * Spring MVC's data binding mechanism requires getter/setter pairs
 * to populate a model object from an HTML form's POST parameters.
 * Without setters, form data cannot be bound to User fields.
 *
 * =====================================================================
 * DESIGN NOTE
 * =====================================================================
 * In production, passwords should be hashed (e.g., BCrypt).
 * For this demo application we store plain text for simplicity.
 * See the service layer comments for where to add hashing.
 */
public class User {

    // Matches: id BIGINT AUTO_INCREMENT PRIMARY KEY
    private Long id;

    // Matches: name VARCHAR(100)
    private String name;

    // Matches: email VARCHAR(100) UNIQUE
    private String email;

    // Matches: password VARCHAR(255)
    private String password;

    // =====================================================================
    // CONSTRUCTORS
    // =====================================================================

    /**
     * No-arg constructor required by Spring MVC's data binding.
     * When Spring sees a @ModelAttribute User user parameter in a
     * controller method, it first calls this constructor, then
     * calls setters for each matching form field.
     */
    public User() {
    }

    /**
     * Convenience constructor for creating a User with all fields.
     * Used in DAOs when reading from ResultSet.
     */
    public User(Long id, String name, String email, String password) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
    }

    /**
     * Constructor without id — useful for INSERT operations
     * where id is auto-generated by the database.
     */
    public User(String name, String email, String password) {
        this.name = name;
        this.email = email;
        this.password = password;
    }

    // =====================================================================
    // GETTERS & SETTERS
    // =====================================================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // =====================================================================
    // UTILITY METHODS
    // =====================================================================

    /**
     * Returns a safe string representation without exposing the password.
     * Important for logging — never log passwords.
     */
    @Override
    public String toString() {
        return "User{" +
               "id=" + id +
               ", name='" + name + '\'' +
               ", email='" + email + '\'' +
               ", password='[PROTECTED]'" +
               '}';
    }
}
